### PR TITLE
fix push of tag

### PR DESCRIPTION
**Pull request by sebastian-toepfer**
required to work with version 4 of checkout action

### CODE REVIEW

**Comment by sebastian-toepfer** [comment]
run with unchanged action:
https://github.com/sebastian-toepfer/gh-common/actions/runs/7438842539
run with my change (c&p):
https://github.com/sebastian-toepfer/gh-common/actions/runs/7440243799

**Comment by sebastian-toepfer** [comment]
@phwt : Can you please take a look at this?

**Comment by phwt** [comment]
Hi @sebastian-toepfer, thanks for the contribution.

I'm not aware of the breaking changes between `v3` and `v4` of `actions/checkout`. Would you mind explaining why `git push --tags` doesn't work with the `v4`?

Also in #3, I see that you added the following permission, maybe you can add on to this as well.

```yaml
permissions: 
  contents: write 
```

**Comment by sebastian-toepfer** [comment]
i`m not sure is it a breaking change or a change in git it self.

but `git push tags` push in my repo both tags. the tag the requested the build and the new created major tag. but this isn't possible.

steps to reproduce:
```
git tag -a v1.2.1
git push --tags
```
Workflow is started, but failed with:
```
To ...
 - [deleted]         v1
To ...
 * [new tag]         v1 -> v1
 ! [rejected]        v1.2.1 -> v1.2.1 (already exists)
```
with this fix, we push no longer any other tag.

**Comment by sebastian-toepfer** [comment]
> Also in #3, I see that you added the following permission, maybe you can add on to this as well.

had split them, so we have the new tag behavior and updating the workflow with the latest checkout action -> which is not necessary for this change. but can merge them.

the permissin is needed now. because the default_github token has no longer pemissions to push to the repo.

**Comment by phwt** [comment]
Thanks for pointing this out, I'll merge your changes into `main` with #4 once it's ready.

**Pull request merged**
